[package]
name = "sea-query-rusqlite-example"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "^0" }
time = { version = "^0.3" }
serde_json = { version = "^1" }
# rusqlite only supports uuid 0
uuid = { version = "^1", features = ["serde", "v4"] }
# that's why we can only use an older version of sea-query
sea-query = { path = "../.." }
sea-query-rusqlite = { path = "../../sea-query-rusqlite", features = [
    "with-chrono",
    "with-json",
    "with-uuid",
    "with-time",
] }

