[package]
name = "sea-query-rusqlite-example"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "^0", default-features = false, features = ["clock"] }
time = { version = "^0.2" }
serde_json = { version = "^1" }
# rusqlite only supports uuid 0
uuid = { version = "^0", features = ["serde", "v4"] }
# that's why we can only use an older version of sea-query
sea-query = { version = "^0.25", features = [
    "rusqlite",
    "with-chrono",
    "with-json",
    "with-uuid",
    "with-time",
] }

[dependencies.rusqlite]
version = "^0.27"
features = [
    "bundled",
    "chrono",
    "serde_json",
    "uuid",
    "time",
]