[package]
name = "sea-query-sqlx-postgres-example"
version = "0.1.0"
edition = "2018"

[dependencies]
async-std = { version = "1.8", features = [ "attributes" ] }
sea-query = { path = "../../", features = ["sqlx-postgres"] }
# NOTE: if you are copying this example into your own project, use the following line instead:
# sea-query = { version = "^0.12", features = ["sqlx-postgres"] }

[dependencies.sqlx]
version = "^0.5"
default-features = false
features = [
    "runtime-async-std-native-tls",
    "macros",
    "postgres",
    "tls",
]
